services:
  # Backend API Service
  - type: web
    name: leetcode-cf-tracker-backend
    runtime: node
    plan: free
    buildCommand: cd server && npm install && npm run build
    startCommand: cd server && npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        fromDatabase:
          name: leetcode-tracker-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        fromService:
          type: web
          name: leetcode-cf-tracker-frontend
          property: host
    autoDeploy: true
    rootDir: .
    
  # Frontend Static Site
  - type: web
    name: leetcode-cf-tracker-frontend
    runtime: static
    plan: free
    buildCommand: cd Leetcode-cf-tracker && npm install && npm run build
    staticPublishPath: ./Leetcode-cf-tracker/dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: leetcode-cf-tracker-backend
          property: host
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    autoDeploy: true
    rootDir: .

databases:
  - name: leetcode-tracker-db
    databaseName: leetcode_tracker
    user: leetcode_user
    plan: free
