[build]
  publish = "dist"
  command = "npm run build"

# API Proxies - Redirect API calls to backend server
[[redirects]]
  from = "/api/*"
  to = "https://your-backend-server.com/api/:splat"
  status = 200
  force = true

# SPA Fallback - Must be last
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin" 